### ISSUE TITLE
Static typing

### ISSUE THREAD

**Issue by DrTobe** [DrTobe/bonglang#11]
From the begin on, we had a statically typed language in mind. Unfortunately, the python environment/implementation made it easy just to omit this in the beginning. Now, this should be introduced. First thing to do: Discuss the syntax.

**Comment by DrTobe** [comment]
Nearly done, only builtin functions missing.

**Comment by DrTobe** [comment]
Additionally, we know how to change the `return` statements now: The `bool` flag that marks if an ast node evaluates to / ends with a return statement should be raplaced by an enum that tells the caller if a node never returns, could return (depending on conditions) or always returns. This can be propagated upwards until a function definition ast node or the top level ast.Program checks if this return type is allowed.

**Comment by DrTobe** [comment]
Normally, we do not specify types for variables but use automatic types derived from the expressions on the rhs of let statements. For empty arrays, which are written as `[]`, this is impossible because the type of the contained values is unknown. What syntax should we use for those cases?

**Todo:**
- [x] Basic syntax discussion: colon+typename for variables, parameters and return types
- [ ] Builtin functions
- [x] Program calls + Pipelines
- [ ] Catch BongtypeExceptions in typechecker and suppress stack traces
- [x] Fix return statement handling
- [ ] Syntax for empty arrays
